Repository Hyp-ed/hyped-2025, pull requests merged in 2025-01, with the labels that each got.

#57 Update README.md
  README.md
Labels: needs-reviews

#14 SNS - I2C Mux (HYPE-13)
  Cargo.lock
  boards/stm32f767zi/Cargo.lock
  boards/stm32f767zi/src/io.rs
  boards/stm32f767zi/src/tasks/temperature.rs
  boards/stm32l432kc/Cargo.lock
  boards/stm32l432kc/src/bin/levitation.rs
  boards/stm32l476rg/Cargo.lock
  boards/stm32l476rg/src/bin/mux_test.rs
  boards/stm32l476rg/src/io.rs
  boards/stm32l476rg/src/tasks/temperature.rs
  lib/core/Cargo.toml
  lib/core/src/format_string.rs
  lib/io/hyped_adc/Cargo.toml
  lib/io/hyped_i2c/hyped_i2c_derive/src/lib.rs
  lib/io/hyped_i2c/src/i2c_mux.rs
  lib/io/hyped_i2c/src/lib.rs
Labels: rewrite, needs-reviews

#58 SNS - I2C Macro
  lib/io/hyped_i2c/src/lib.rs
  lib/sensors/src/temperature.rs
Labels: needs-reviews

#11 INFRA - CAN Board Testing Code (HYPE-15)
  Cargo.lock
  boards/stm32f767zi/src/bin/can_recv.rs
  boards/stm32f767zi/src/bin/can_send.rs
Labels: question, needs-testing

#60 INFRA - Use `Watch` primitive for publishing sensor values
  boards/stm32f767zi/Cargo.lock
  boards/stm32f767zi/Cargo.toml
  boards/stm32f767zi/src/bin/keyence_test.rs
  boards/stm32f767zi/src/bin/temp_test.rs
  boards/stm32f767zi/src/bin/temperature_test.rs
  boards/stm32f767zi/src/tasks.rs
  boards/stm32f767zi/src/tasks/read_keyence.rs
  boards/stm32f767zi/src/tasks/read_temperature.rs
  boards/stm32l476rg/Cargo.lock
  boards/stm32l476rg/Cargo.toml
  boards/stm32l476rg/src/bin/keyence_test.rs
  boards/stm32l476rg/src/bin/temp_test.rs
  boards/stm32l476rg/src/bin/temperature_test.rs
  boards/stm32l476rg/src/tasks.rs
  boards/stm32l476rg/src/tasks/read_keyence.rs
  boards/stm32l476rg/src/tasks/read_temperature.rs
  lib/sensors/src/lib.rs
Labels: question, needs-reviews
